<?php
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;

/* ==========================================================================
  HOOKS
  ========================================================================== */

/**
 * Redirects nodes to edit form on for save.
 */
function evinyl_album_preprocess_node() {
  $parameters = \Drupal::routeMatch()->getParameters()->all();

  if (isset($parameters['node'])) {
    $node = $parameters['node'];
    $id = $node->id();
    $url = Url::fromRoute('entity.node.edit_form', ['node' => $node->id()])->toString();

    // Redirecting to edit.
    $response = new RedirectResponse($url);
    $response->send();

  } elseif (isset($parameters['taxonomy_term'])) {

    $term = $parameters['taxonomy_term'];
    $id = $term->id();
    $url = Url::fromRoute('entity.taxonomy_term.edit_form', ['taxonomy_term' => $id])->toString();

    // Redirecting to edit.
    $response = new RedirectResponse($url);
    $response->send();
  }
}

/**
 * Redirects Drupal's node views pages to the NUXTJS front end.
 */
// function evinyl_user_preprocess_user(&$variables) {
function evinyl_user_entity_view(&$build, $entity) {

  var_dump($entity->getEntityTypeId());
  // $current_path = \Drupal::service('path.current')->getPath();
  // $node_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  // $host = \Drupal::request()->getHost();
  //
  // if ($host === 'localhost' || $host === 'evinyl-cms.test') {
  //   $redirect = 'http://localhost:3000' . $node_alias;
  // } elseif ($host === 'cms.evinyl.net') {
  //   $redirect = 'http://evinyl.net' . $node_alias;
  // } else {
  //   $redirect = 'https://dev.evinyl.net' . $node_alias;
  // }
  //
  // \Drupal::logger('evinyl_user')->notice('Redirecting user page ' . $redirect);
  //
  // $response = new Symfony\Component\HttpFoundation\RedirectResponse($redirect, 301);
  // $response->send();
  // Drupal::entityTypeManager()->getViewBuilder('node')->resetCache();
}
