<?php

use Symfony\Component\HttpFoundation;

/* ==========================================================================
  HOOKS
  ========================================================================== */
function evinyl_user_preprocess_user(&$variables){
  $current_path = \Drupal::service('path.current')->getPath();
  $node_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  $host = \Drupal::request()->getHost();
  if ($host == 'localhost') {
    $redirect = 'http://localhost:3000' . $node_alias;
  } else {
    $redirect = 'https://evinyl.net' . $node_alias;
  }

  $response = new Symfony\Component\HttpFoundation\RedirectResponse($redirect);
  $response->send();
  Drupal::entityTypeManager()->getViewBuilder('node')->resetCache();
  return;
}
