<?php

/* ==========================================================================
  HOOKS
  ========================================================================== */
function evinyl_user_preprocess_user(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $node_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  $host = \Drupal::request()->getHost();

  if ($host === 'localhost') {
    $redirect = 'http://localhost:3000' . $node_alias;
  } elseif ($host === 'cms.evinyl.net') {
    $redirect = 'http://evinyl.net' . $node_alias;
  } else {
    $redirect = 'https://dev.evinyl.net' . $node_alias;
  }

  \Drupal::logger('evinyl_user')->notice('Redirecting user page ' . $redirect);

  $response = new Symfony\Component\HttpFoundation\RedirectResponse($redirect, 301);
  $response->send();
  Drupal::entityTypeManager()->getViewBuilder('node')->resetCache();
}
